### ISSUE TITLE
Is createSmartAction not exported from the es module?

### ISSUE THREAD

**Issue by mcmichaelchan** [klis87/redux-smart-actions#21]
Hi @klis87, thank you for the amazing library. When I import `createSmartAction` in my react project, I encountered the following question.
![image](https://user-images.githubusercontent.com/15685780/137280841-7c6e807f-bb8f-471e-8631-3a90d57f960a.png)

**Comment by klis87** [comment]
@mcmicahelchan Hi, I am glad you like it! Actually it is not! For smart actions and thunks you must use https://github.com/klis87/redux-smart-actions#babel-plugin . It just converts smart imports into casual ones. Such a functionality unfortunately is not possible witout Babel plugin.

It is however covered in Typescript types, so if you have Babel plugin in your setup, you will get proper autocomplete in your text editor, as well as type checking for `createSmartAction` and `createSmartThunk`.

**Comment by mcmichaelchan** [comment]
Thx!
